# Generated by Django 2.1.2 on 2018-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('bpubdate', models.DateField()),
                ('bprice', models.FloatField()),
                ('bnumber', models.IntegerField()),
            ],
        ),
    ]
